- name: demo on play level variables
  hosts: localhost
  connection: local # it will not ask for username and password
  vars:
    COURSE: "Ansible"
    NAME: "Nanda"
    DURATION: "150HRS"
  tasks:
  - debug:
      msg: "Hi, I am learning {{ COURSE }}, name is {{ NAME }}, Duration is {{ DURATION }}"