- name: demo on vars_files
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: print variables information
    debug:
      msg: "Hi, I am learning {{ COURSE }}, name is {{ NAME }}, Duration is {{ DURATION }}"